### ISSUE TITLE
Auto-scaling support for Aurora Postgres

### ISSUE THREAD

**Issue by kitsirota** [awslabs/aws-advanced-jdbc-wrapper#273]
### Describe the feature

When running deployments using the JDBC wrapper against auto-scaling enabled clusters, we have observed that when the cluster scales up, all the existing connections remain with the instances that they were attached to and the new instances added by auto-scaling are never utilized.

Given that we are able to track cluster topology changes over time and we are able to determine which connections are currently active, it should be possible to add support for re-balancing connections across read replicas in scale up and down events.  

### Use Case

When running our deployments with the vanilla jdbc driver configuration, scale up events seem to get a relatively even distribution of connections/requests across all the nodes in the autoscaling group (including new nodes that were provisioned when the cluster is under load).  The downside is this requires us to run very aggressive health checks to ensure that when the cluster scales down the read replica pool, our deployments are able to quickly detect when their connections to the cluster are dead and re-establish them.  This polling approach does result in failed requests in down scaling scenarios and therefore this limits the use-cases to background jobs that are able to resume when some subset of DB requests fail.

In a ideal scenario, knowledge of the cluster topology changes should enhance the application's ability to move inactive connections during auto-scaling events.  Especially in the case of high throughput, low latency requests, this would enable the cluster to accommodate the needs of the applications that rely on application-level auto-scaling (horizontal pod auto-scaling).

### Proposed Solution

One idea would be to assign connections to a read-only endpoint across all the reader instances in a round robin fashion.  Then periodically re-evaluate the cluster topology and when a scale up/down event occurs, gracefully rebalance the connections that are not currently in use across the latest state of the cluster.  

An additional measure to mitigate downtime during scale down events could be to pin a percentage of the connections in a connection pool to the fixed instances in the cluster, this way a subset of connections is guaranteed to be available to the application for ongoing requests.  While this may temporarily limit throughput, it ensures that the connections left for auto-scaling are able to readily move to new nodes to take load off of the fixed instances.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### The AWS Advanced JDBC Driver version used

1.0.0

### JDK version used

jdk-17.0.5+8

### Operating System and version

Ubuntu 20.04

**Comment by davecramer** [comment]
@kitsirota May I ask which plugins you have enabled when you tried this?
My expectation is that this should already work with the efm plugin.

**Comment by hsuamz** [comment]
Hello @kitsirota,

Following up from Dave's response. Would you be able to list the plugins you have enabled? Have you also looked into the [EFM (Host Monitoring Plugin)](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/using-plugins/UsingTheHostMonitoringPlugin.md)?

Thanks.

**Comment by kitsirota** [comment]
Apologies for the delayed response.  We have been testing with the following plugins

failover, efm, auroraStaleDns, auroraHostList, logQuery

**Comment by karenc-bq** [comment]
Hi @kitsirota, thank you for the response, we have some follow up questions:

1. Would you be able to provide some logs? https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#logging
2. Can you please provide an example of your connection string?
3. Were the plugins specified in the exact order you provided us? (i. e. `failover, efm, auroraStaleDns, auroraHostList, logQuery`)
4. Are you using connection pools?
5. How are you handling failover exceptions? Here is a list of the failover exceptions for your reference: https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/using-plugins/UsingTheFailoverPlugin.md#failover-exception-codes

**Comment by kitsirota** [comment]
@karenc-bq Thanks so much for the questions, we need to get the test bench back up and running to get you all the answers.  I'll post with answers as soon as possible.

**Comment by TurbulentCupcake** [comment]
@karenc-bq I work with @kitsirota . Thanks again for the questions. While we work to get you the logs, we can answer some of them: 

2. Our connection string is as follows: `jdbc-wrapper-test.cluster-ro-xyz.us-east-1.rds.amazonaws.com/`
3. Yep, plugins are specified in that exact order: `failover, efm, auroraStaleDns, auroraHostList, logQuery`
4. Yes, we do use Hikari CP for connection pooling. In fact, we based our test bench off the example here: https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/examples/HikariExample/src/main/java/software/amazon/HikariFailoverExample.java
5. At the moment, we don't have any sort of exception handling since we're trying to observe and understand the wrapper's behavior in test.

**Comment by TurbulentCupcake** [comment]
Hi Folks, just following up on this discussion. I'd like to clarify the expectation of how the EFM plugin is meant to work in the issue as described by @kitsirota at the top of the thread:

Assuming the client is connected to an overloaded instance (Node A) and the autoscaler kicks in - thus adding a new RO instance (Node B), the `efm` plugin will detect (based on parameters set for `failureDetectionTime`, `failureDetectionInterval` and `failureDetectionCount`) that its connection to Node A has timed out thus aborting the connection, marking the connection as unhealthy and setting its availability to `HostAvailability.NOT_AVAILABLE`. This in turn will cause Hikari to replenish its connection pool by creating a new connection using the `AwsWrapperDataSource`. While attempting to establish a new connection, the `AwsWrapperDataSource` will establish a connection with Node B, which would be determined to be healthy.

Is my understanding correct?

**Comment by karenc-bq** [comment]
Hi @TurbulentCupcake, yes your understanding is correct.

To go back to the original feature request and to clarify, auto-scaling is already handled by the Wrapper driver. To further clarify, there are three different things that can happen during a scale up/down event when the application is using cluster endpoints:

1. For existing and active connections, as you described, the EFM plugin will detect a connectivity issue and triggers HikariCP to connect to Node B.
2. For idle connections in the connection pool, while the change in topology is not immediately recognized, if the application attempts to use the idle connection while Node A is still down, EFM will again detect the error the trigger a new connection to Node B.
3. For new connections, Aurora will automatically establish the connection to an active and healthy node when using cluster endpoints.

Please let us know if this clarifies your understanding and thank you for providing feedback.

**Comment by davecramer** [comment]
@TurbulentCupcake When you scale up, how many readers do you add ?

**Comment by kitsirota** [comment]
@davecramer In our testing scenario, we used an auto-scaling policy configured to add 1 to 4 readers when the average CPU utilization for the read replicas exceeds 50% (screenshot of the policy attached below).  The cluster contains 1 writer and 1 reader by default and additional readers are added as part of this auto-scaling policy.

The load test we ran repeated the same query with a consistent 300ms delay between executions and a concurrency factor of 2 for the first 15 minutes, then doubling and running for another 45 minutes.  This resulted in a consistent CPU utilization of about 70% across the initial reader instance for the first 15 minutes, and 100% utilization for the remaining 45 minutes.  As new readers were added, we observed these instances sitting idle as all of the existing connections in the hakari pool remained on the initial reader instance.  

![image](https://user-images.githubusercontent.com/3009800/220407959-dd6e70d7-2337-4d5a-9df7-ba3442ac4516.png)

The aspect of this that I am not entirely sure about is if we should move off of Hakari for reader connection pooling as this would enable these connections to organically distribute across all the available readers behind the reader endpoint as requests come in.  

One of the tradeoffs when going pool-less is we would lose the ability to control the number of concurrent connections our services may open up, resulting in unpredictable spikes in connection counts and even saturating the max_connection limits on the readers and resulting in a different set of equally serious problems.  On the other hand, its also not entirely clear that managing connection pools and redistributing connections when the cluster topology changes should be delegated outside of Hakari.

**Comment by davecramer** [comment]
@kitsirota thanks for the info. We are using this information for future design considerations.

**Comment by TurbulentCupcake** [comment]
Hi folks, couple of additional questions while we peruse the codebase: 
1. Does the JDBC driver utilize any aurora api's or does it rely purely on database queries to determine topology?
2. In the `PG_RETRIEVE_TOPOLOGY_SQL` query used to determine the topology, how is the `LAST_UPDATE_TIMESTAMP` being set ? Is this simply the last read/write to that specific instance?

**Comment by davecramer** [comment]
> Hi folks, couple of additional questions while we peruse the codebase:
> 
> 1. Does the JDBC driver utilize any aurora api's or does it rely purely on database queries to determine topology?
Database query
> 2. In the `PG_RETRIEVE_TOPOLOGY_SQL` query used to determine the topology, how is the `LAST_UPDATE_TIMESTAMP` being set ? Is this simply the last read/write to that specific instance?
This is the last time the topology was updated.

**Comment by TurbulentCupcake** [comment]
@davecramer why are we going through the database instead of going through the control plane to determine topology? Is there an api endpoint to determine cluster state?

**Comment by davecramer** [comment]
@TurbulentCupcake  The database is the source of truth.

**Comment by TurbulentCupcake** [comment]
@davecramer
1. When a failover is performed, is this performed at the database level or through an external control plane/observer?
2. Independent of the aws-advanced-jdbc-wrapper: If a writer is in failover, presumably it is unable to update its tables to indicate the new topology. So the only place we could query is the reader, which might not have the latest state of the cluster because no new data could have been ingested during the failover. So, how is the database updated with the latest topology such that it can be retrieved through `aurora_replica_status()`? Is it that one of the readers determines that the cluster state is broken and attempts to update its internal tables to reflect the new cluster?

**Comment by davecramer** [comment]
> @davecramer
> 
> 1. When a failover is performed, is this performed at the database level or through an external control plane/observer?

This is done through a control plane/observer

> 2. Independent of the aws-advanced-jdbc-wrapper: If a writer is in failover, presumably it is unable to update its tables to indicate the new topology. So the only place we could query is the reader, which might not have the latest state of the cluster because no new data could have been ingested during the failover. So, how is the database updated with the latest topology such that it can be retrieved through `aurora_replica_status()`? Is it that one of the readers determines that the cluster state is broken and attempts to update its internal tables to reflect the new cluster?

Excellent question!  Aurora has shared status among the readers and the writer, so regardless which node you are reading you see the same thing. What happens is when failover occurs all nodes go down (in APG at least) and the writer comes up first and then the reader(s). The first node the wrapper connects to will be the new writer and `aurora_replica_status()` reflects this.

Hope this helps.

**Comment by TurbulentCupcake** [comment]
@davecramer just to clarify your answer to the first question, is it the case that writer election is done by the control plane and not elected through the remaining nodes within the cluster?

**Comment by davecramer** [comment]
@TurbulentCupcake I will have to check, but I'm pretty sure this is the case.

**Comment by davecramer** [comment]
So the answer is that the CP determines the new writer.
Also someone pointed out that the API is rate limited so using the API would have other issues.
It's also not current.

**Comment by TurbulentCupcake** [comment]
@davecramer When discovering topology, why do we filter out nodes that haven't been updated in the last 5 minutes?
```
      "SELECT SERVER_ID, SESSION_ID FROM aurora_replica_status() "
          // filter out nodes that haven't been updated in the last 5 minutes
          + "WHERE EXTRACT(EPOCH FROM(NOW() - LAST_UPDATE_TIMESTAMP)) <= 300 OR SESSION_ID = 'MASTER_SESSION_ID' "
          + "ORDER BY LAST_UPDATE_TIMESTAMP";
```

**Comment by davecramer** [comment]
@TurbulentCupcake if they haven't been updated then nothing has changed. In reality though they are updated much more often than 5 minutes. More like every couple of seconds.

**Comment by TurbulentCupcake** [comment]
@davecramer thanks for answering my questions so far! 

1. Could you clarify this in the case of a two node cluster, where node A is the writer and node B is the reader. When node A goes through a failover, node B becomes the writer. Based on what you're suggesting it sounds like the client connection would have some impact on the writer election process? 

   > The first node the wrapper connects to will be the new writer and `aurora_replica_status()` reflects this

2. In a healthy cluster, rerunning the `PG_RETRIEVE_TOPOLOGY_SQL` query several times shows that the last updated timestamp is updated every couple of seconds, what does that tell us if there is no failover occurring? Is there a case where a node's `LAST_UPDATE_TIMESTAMP` does not get updated? What condition are we looking to isolate with the 5 minute time limit? 

3. Back to the API discovery mode, we came across another project that does something similar but specifically for autoscaling read-replicas. Unfortunately, this project is no longer maintained. Im curious if it makes sense to pull some of the ideas in this project into the jdbc wrapper https://github.com/DiceTechnology/dice-fairlink. In the case of this project, they offer two modes of member discovery: [one via the API and a fallback](https://github.com/DiceTechnology/dice-fairlink#member-discovery)  via the `aurora_replica_status()` function. They also mention the rate limiting problem and the workaround to it. Is there something about their approach that would not make sense to include as part of the cluster topology discovery strategy in this project? 

4. As we understand it, Route53 doesn't follow the RFC spec round-robin mechanism [1]. Instead, responses are rotated once every second and not per request, which would significantly deviate from what you would expect to see in an on-prem deployment. Based on this when an aurora connection pool is established, every member of that connection pool will have the same host instead of getting round-robin distribution across the available nodes. This brings back the question of how these connection strings are built? If the cluster topology is known, then when Hikari is establishing a connection pool, why is the same host passed in for all the connections in a connection pool? Is this a DNS issue? Or is this a case of us not using the cluster topology information that we get back from the database to evenly distribute connections across the available readers? 

5. From the JDBC wrapper's perspective, what is meant by a reader failover? Is it simply defined as a case where the reader fails to respond to queries or if a query hits the query timeout threshold? Could you describe from the context of a client, why does it matter if it is a reader or a writer failover? A failover in any event results in all clients having to reconnect, therefore shouldn't all connection pools have to reconnect to the correct their respective cluster members i.e read pools -> reader, write pools -> writer? 

6. In all of the testing we've done so far on a two or three node clusters, regardless of whether we use `strictReaderFailoverEnabled` toggle, all reader pools favor the writer node after the connection pool is reestablished. It is unclear to us why this is happening, but from what we can tell instrumenting against our reader pools, we find ourselves in a failover loop where we consistently overload the writer while the reader's sit idle. It is unclear to us why this is happening, resulting in our asking these fundamental questions to validate our understanding.

References:
[1] https://github.com/DiceTechnology/dice-fairlink#why-do-we-need-dice-fairlink-long-version
