### ISSUE TITLE
feat: Default Profile for Plugin Order

### ISSUE THREAD

**Issue by hsuamz** [awslabs/aws-advanced-jdbc-wrapper#330]
# Description

- Implement a default profile in which plugins and ordering are optimal to improve the "out of the box" experience.

# Design

If no wrapper plugin codes were specified as part of the configuration parameters, the driver will use a default list of plugin codes:
https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/wrapper/src/main/java/software/amazon/jdbc/ConnectionPluginManager.java#L175

This list is currently empty but we propose to include the following plugins:
- auroraConnectionTracker, a new plugin to track opened connections and handle impacted connections after a failover. It is pending to be merged in PR #298
- failover 
- efm

**Comment by karenc-bq** [comment]
@davecramer do you have any thoughts on which wrapper plugins we should include in the default plugin profile?

**Comment by davecramer** [comment]
the driver should failover, so failover and efm at a minimum

**Comment by karenc-bq** [comment]
The failover connection plugin requires Aurora-specific SQL functions to query topology. If user application connects to a generic database with the failover connection plugin enabled, they will encounter a `SQLSyntaxErrorException`.

This wasn't an issue when users had to opt-in for failover connection plugin, which indicates they are aware that the failover plugin is Aurora-specific. However, if we were to make the failover connection plugin a default plugin, first-time users that are just trying out the driver on their local generic databases would see an exception on their first try. 

There are 2 solutions to this issue:
1. Keep the current behaviour. Throw the syntax exception. Users would have to opt-out of the failover connection plugin if they wish to connect to a generic database.
2. Ignore the syntax exception, and have failover disabled since the wrapper cannot retrieve the cluster topology. If a network error occurs, instead of trigger failover, the failover connection plugin will just propagate the error to the user application instead of triggering failover.

After an internal discussion we have decided to go with the first solution for the following reasons:
1. users would be immediately aware of the incompatibility so they can handle it appropriately
2. removes potential confusion when failover is not initiated even though failover connection plugin was enabled.
