### ISSUE TITLE
feat: Support MariaDB JDBC Connector

### ISSUE THREAD

**Issue by davecramer** [awslabs/aws-advanced-jdbc-wrapper#341]
### Describe the feature

Currently jdbc scheme's are hard coded to postgres and mysql.  Remove hard coded schemes in favour of a dialect

### Use Case

no support for mariadb

### Proposed Solution

use a dialect to figure out which one to load

### Other Information

#342 

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### The AWS Advanced JDBC Driver version used

Latest

### JDK version used

1.8

### Operating System and version

any

**Comment by karenc-bq** [comment]
Thank you for logging this enhancement @davecramer.

Could we clarify the request? The failover plugin is only applicable for Aurora. Since MariaDB is not part of Aurora, the wrapper’s hard coded JDBC Schemes only apply to failover plugin functionality. Would rebranding this ticket as "A dialect implementation to remove hardcoded JDBC schemes" be more along the lines of this proposed enhancement?

For context, the Wrapper is compatible with the MariaDB JDBC driver and we're working through testing verification before we claim official support.

**Comment by karenc-bq** [comment]
Dialect changes merged  in PR #372, closing this ticket now.
