### ISSUE TITLE
Unable to acquire JDBC Connection from Read Only Hikari connection pool

### ISSUE THREAD

**Issue by william00179** [awslabs/aws-advanced-jdbc-wrapper#512]
### Describe the bug

Our Spring Boot services use two Hikari CP connection pools, one for RW connections, and one for RO connections. The correct datasource is fetched at runtime depending on the needs of the transaction. 

The RW pool is connected to the writer cluster endpoint, and the RO pool is connected to the reader cluster endpoint.

After a relatively short period of time (<1hr of the pool starting) it will start throwing `Unable to acquire JDBC Connection` only in the RO pool. Even at very low load.

This issue doesn't happen if the plain Postgres JDBC driver is used.

### Expected Behavior

The read only pool would continue to operate like the read-write pool does.

### What plugins are used? What other connection properties were set?

failover,efm,auroraConnectionTracker,driverMetaData

### Current Behavior

After a short (<1hr) period of time, the read-only connection pool will start to timeout getting connections even with very low load on the system.

### Reproduction Steps

The following properties are being set
```
SPRING_DATASOURCE_DRIVERCLASSNAME                                 = "software.amazon.jdbc.Driver"
SPRING_DATASOURCE_HIKARI_DATASOURCEPROPERTIES_WRAPPER_PLUGINS     = "failover,efm,auroraConnectionTracker,driverMetaData"
SPRING_DATASOURCE_HIKARI_DATASOURCEPROPERTIES_WRAPPER_DIALECT     = "aurora-pg"
SPRING_DATASOURCE_HIKARI_DATASOURCEPROPERTIES_WRAPPER_DRIVER_NAME = "PostgreSQL JDBC Driver"
SPRING_DATASOURCE_HIKARI_EXCEPTIONOVERRIDECLASSNAME              = "software.amazon.jdbc.util.HikariCPSQLException"
SPRING_DATASOURCE_HIKARI_TARGET_DATA_SOURCE_CLASS_NAME              = "org.postgresql.ds.PGSimpleDataSource"
      ```

### The AWS Advanced JDBC Driver version used

2.2.1

### JDK version used

openjdk 20.0.1 2023-04-18 OpenJDK Runtime Environment Temurin-20.0.1+9 (build 20.0.1+9) OpenJDK 64-Bit Server VM Temurin-20.0.1+9 (build 20.0.1+9, mixed mode, sharing)

### Operating System and version

eclipse-temurin:20-jre

**Comment by crystall-bitquill** [comment]
Hi @william00179,

Thanks for reaching out and raising this issue.

We'll take a look at this and keep you updated as we investigate.

Thank you for your patience!

**Comment by brunos-bq** [comment]
Hi @william00179,
thank you for providing us with all these information.

We are currently investigating this issue. During the meantime, could you please answer the following questions to help us with the investigation:

1. Do you see the same issue if you invert the order of the plugins?
We would suggest using the following order for the plugin list: `SPRING_DATASOURCE_HIKARI_DATASOURCEPROPERTIES_WRAPPER_PLUGINS     = "driverMetaData, auroraConnectionTracker, failover, efm"`
2. Does your DataSourceBuilder implementation use `PGSimpleDataSource` internally or does it use a connection pool datasource?
3. In order to verify if there is any particular configuration causing the issue on the Hikari side, would you be able to provide HikariConfig logs? (ie. `DEBUG com.zaxxer.hikari.HikariConfig`)
4. Also, are you able to provide us with any driver logs? You can enable logs by adding this directly to your code snippet: targetDataSourceProps.setProperty("wrapperLoggerLevel", "FINEST"); See https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#logging for more information.

**Comment by aaronchung-bitquill** [comment]
Hi @william00179 

I wanted to check in and see if there are any updates? 

If there are no further updates on this ticket in the next 3 days, we will close this ticket. However, if you require further assistance, you can reopen this issue, or create a new one.

Thank you!
