### ISSUE TITLE
Include an example of how to configure the Spring DataSourceTransactionManager

### ISSUE THREAD

**Issue by dlesl** [awslabs/aws-advanced-jdbc-wrapper#608]
### Describe the feature

Hi,

Thanks for providing the example projects that demonstrate how to integrate the wrapper with Spring. It would be great if you could add an example of how to recover from a failover too, especially when transactions are used. I found it's a bit tricky to handle failovers in combination with Spring's transaction management. At least when using Aurora PostgreSQL it seems that there is an issue when a `FailoverSQLException` is thrown during commit - we end up [here](https://github.com/spring-projects/spring-framework/blob/baf367831fa0cc9f70eac0f9bf9f8a3ed09f760c/spring-tx/src/main/java/org/springframework/transaction/support/AbstractPlatformTransactionManager.java#L828) (even when `rollbackOnCommitFailure` is false). That tries to issue a rollback, which the PG JDBC driver objects to (since it is in fact a new connection and no transaction is in progress). The original `FailoverSQLException` [is then discarded](https://github.com/spring-projects/spring-framework/blob/baf367831fa0cc9f70eac0f9bf9f8a3ed09f760c/spring-tx/src/main/java/org/springframework/transaction/support/AbstractPlatformTransactionManager.java#L969) leaving no way for application code to detect the failover and retry the transaction.

I was able to work around it like this (there is no rollback attempt when the exception thrown is a `TransactionException`), but perhaps there is a better way?

```java
  @StandardException
  public static class FailoverDuringTransactionException extends TransactionException {}

  @Bean
  DataSourceTransactionManager transactionManager(DataSource dataSource,
                                                  ObjectProvider<TransactionManagerCustomizers> transactionManagerCustomizers) {
    var transactionManager = new JdbcTransactionManager(dataSource) {
      @Override
      protected RuntimeException translateException(String task, SQLException ex) {
        if (ex instanceof FailoverSQLException) {
          // We need to translate this to a subclass of `TransactionException` so that 
          // `AbstractPlatformTransactionManager::processCommit` doesn't attempt to issue a rollback
          throw new FailoverDuringTransactionException(task + " failed", ex);
        }
        return super.translateException(task, ex);
      }
    };
    transactionManagerCustomizers.ifAvailable((customizers) -> customizers.customize(transactionManager));
    return transactionManager;
  }
```

### Use Case

It would be great to be able to retry transactions after a failover

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### The AWS Advanced JDBC Driver version used

2.2.3

### JDK version used

17

### Operating System and version

AL2023

**Comment by crystall-bitquill** [comment]
Hi @dlesl,

Thank you for reaching out and raising this issue.

We'll take a look at this and keep you updated as we investigate.

Thank you for your patience!

**Comment by crystall-bitquill** [comment]
Hi @dlesl, 

To update you, we've been looking into adding additional code examples.

In the meantime, would it be possible for you to provide additional details regarding the following?
1. Driver logs, which can be enabled as seen [here](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#logging).
2. A snippet of sample code if possible, to see how you're reaching the points mentioned in the `AbstractPlatformTransactionManager`.
3. What version of Spring are you using?
4. Are you using global transactions, by any chance? The driver unfortunately does not support global transactions.

Thank you!

**Comment by dlesl** [comment]
Hi @crystall-bitquill, thanks for looking into this. 

> Driver logs, which can be enabled as seen [here](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#logging).

Unfortunately I haven't had a chance to do this yet, but if you think the example below isn't sufficient I should be able to find time at some point.

> A snippet of sample code if possible, to see how you're reaching the points mentioned in the AbstractPlatformTransactionManager.

I've put together a sample [here](https://github.com/dlesl/aws-advanced-jdbc-wrapper-spring-transaction-example) which runs against a dockerised vanilla postgres instance but uses Mockito to activate the same code paths I observed during a failover against an Aurora Cluster. If you disable `DataSourceTransactionManagerConfig` you will see the problematic behaviour.

> What version of Spring are you using?

3.1.2 (the example uses 3.1.3 which behaves the same)

> Are you using global transactions, by any chance? The driver unfortunately does not support global transactions.

 nope

Please let me know if there is anymore information I can provide and I will do my best! Thanks!

**Comment by crystall-bitquill** [comment]
Hi @dlesl,

Thank you for providing a sample!

To update you, we've merged two PRs that are related to this issue.

[PR #632](https://github.com/awslabs/aws-advanced-jdbc-wrapper/pull/632) introduces a new connection property `keepSessionStateOnFailover`. This parameter allows connections to keep a partial session state after failover including the autocommit and read only values. This was necessary because after failover, a reestablished connection will have its session state reset and the connection would require manual reconfiguring. This meant that in applications where manually reconfiguring connections was not possible or would be difficult, like in a Spring application, a connection with the autocommit value set to false would then have the autocommit value set to true. This would cause issues like the one in the sample you created, with messages like "Cannot rollback when autoCommit is enabled". This change is available in the latest [snapshot build](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#using-a-snapshot-of-the-driver) and should allow the failover exceptions to be thrown properly.

[PR #638](https://github.com/awslabs/aws-advanced-jdbc-wrapper/pull/638) is a simple example Spring application using transactions and retries in case of failover. It uses the `keepSessionStateOnFailover` parameter and does not require any specific DataSourceTransactionManager configuration to function.
